/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code401challenges;
import java.lang.*;

public class Library {
//    public boolean someLibraryMethod() {
//        return true;
//    }

    public class ArrayShift {
        public static int[]insertShiftArray (int[] starting )
    }


}




/////////psudo code///////
input array = [1,5,7,3,12]
        new value = 10
        new array = []
        midpoint = input array lenght/2

        insert shift array (input arary, new value)
        for [i] if i != midpoint
        add [i] to new array
        if i = midpoint
        add new value to to new array then add [i]
        return new array

public static


////

CC02:

public class ArrayShift {
    public static int[] insertShiftArray(int[] startingArray, int valueToAdd) {
        int[] newArray = new int[startingArray.length+1];
        int midPoint = startingArray.length/2;
        int n = 0;
        for(int i =0; i<newArray.length; i++){
            if(i != midPoint ){
                newArray[i] = startingArray[n];
                n++;
            }else{
                newArray[i] = valueToAdd;
            }
        }
        System.out.println(Arrays.toString(newArray));
        return newArray;
    }
}


